echo "( Wielka moc to wielka odpowiedzialność!. )"
echo " ---------------------------------         "
echo "        o   ^__^                           "
echo "         o  (oo)\_______                   "
echo "            (__)\       )\/\               "
echo "                ||----w |                  "
echo "                ||     ||                  "
echo "                                           "
echo "Ta konsola ma moce Super Krowy.            "
